# KNN - Vizinhos Mais Próximos

In [34]:
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KDTree
import numpy as np

# Conjunto de Dados em um espaço 2D
x = np.array([[-10, -5], [-2, -1], [-3, -2], [5, 4], [7, 2], [3, 4]])

# Cria e treina o Modelo 
"""
> n_neighbors=2        : Encontrar os 2 Vizinhos mais próximos.
> algorithm='ball_tree': O algorítimo usado para encontrar os Vizinhos.
> .fit(x)              : Estrutura dos dado que o modelo aprende.
"""
vizinhos = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(x)


# Encontra as Diatâncias e os Indices dos 'K' Vizinhos mais próximos para cada ponto X.
distances, indices = vizinhos.kneighbors(x)
print(indices)

[[0 2]
 [1 2]
 [2 1]
 [3 5]
 [4 3]
 [5 3]]


In [35]:
print(distances)

[[0.         7.61577311]
 [0.         1.41421356]
 [0.         1.41421356]
 [0.         2.        ]
 [0.         2.82842712]
 [0.         2.        ]]


In [36]:
vizinhos.kneighbors_graph(x).toarray()

array([[1., 0., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 0., 1.]])

In [45]:
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
kdt = KDTree(X, leaf_size=30, metric='euclidean')
kdt.query(X, k=2, return_distance=False)

array([[0, 1],
       [1, 0],
       [2, 1],
       [3, 4],
       [4, 3],
       [5, 4]])

In [46]:
from sklearn.neighbors import KDTree, BallTree
KDTree.valid_metrics
BallTree.valid_metrics

['euclidean',
 'l2',
 'minkowski',
 'p',
 'manhattan',
 'cityblock',
 'l1',
 'chebyshev',
 'infinity',
 'seuclidean',
 'mahalanobis',
 'hamming',
 'canberra',
 'braycurtis',
 'jaccard',
 'dice',
 'rogerstanimoto',
 'russellrao',
 'sokalmichener',
 'sokalsneath',
 'haversine',
 'pyfunc']